In [6]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [7]:
file = 'Profil-Kesehatan-Indonesia-tahun-2017.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (90, 80, 450, 520), pages = '63', columns=[0])
df = data[0]
df = df.iloc[1:, [1]]
df

   RASIO PUSKESMAS PER KECAMATAN DI INDONESIA
1                            DKI Jakarta 7,73
2                                   Bali 2,11
3                       Kalimantan Timur 1,74
4                                 Maluku 1,69
5                             Jawa Barat 1,68
6                          DI Yogyakarta 1,55
7                            Jawa Tengah 1,53
8                     Kalimantan Selatan 1,50
9                                 Banten 1,50
10                        Sumatera Barat 1,50
11                      Sulawesi Selatan 1,47
12                            Jawa Timur 1,45
13                     Kalimantan Tengah 1,44
14                              Bengkulu 1,41
15                      Kalimantan Barat 1,39
16                   Nusa Tenggara Barat 1,38
17                      Sumatera Selatan 1,36
18                        Sulawesi Barat 1,36
19             Kepulauan Bangka Belitung 1,34
20                                 Jambi 1,32
21                               Lampung 1,30
22                                  Riau 1,30
23                        Sumatera Utara 1,29
24                     Sulawesi Tenggara 1,25
25                             Gorontalo 1,21
26                   Nusa Tenggara Timur 1,20
27                                  Aceh 1,18
28                          Maluku Utara 1,12
29                        Sulawesi Utara 1,11
30                       Sulawesi Tengah 1,10
31                        Kepulauan Riau 1,06
32                      Kalimantan Utara 0,92
33                           Papua Barat 0,71
34                                 Papua 0,70

In [8]:
# df.columns = np.arange(2)
# jakarta = df.iloc[2,:]
# df = df.iloc[1:]
# df

# df[1] = df[0].str.split(' ').str[-1]
# df[0] = df[0].str.split(' ').str[:-1].str.join(' ')
# df

concat = df.copy()
split = concat.iloc[:,0].str.split(' ')
# isna = concat[1].isna()
concat.loc[:, 1] = split.str[-1]
concat.iloc[:, 0] = split.str[:-1].str.join(' ') 
# concat.columns = np.arange(2)
concat

   RASIO PUSKESMAS PER KECAMATAN DI INDONESIA     1
1                                 DKI Jakarta  7,73
2                                        Bali  2,11
3                            Kalimantan Timur  1,74
4                                      Maluku  1,69
5                                  Jawa Barat  1,68
6                               DI Yogyakarta  1,55
7                                 Jawa Tengah  1,53
8                          Kalimantan Selatan  1,50
9                                      Banten  1,50
10                             Sumatera Barat  1,50
11                           Sulawesi Selatan  1,47
12                                 Jawa Timur  1,45
13                          Kalimantan Tengah  1,44
14                                   Bengkulu  1,41
15                           Kalimantan Barat  1,39
16                        Nusa Tenggara Barat  1,38
17                           Sumatera Selatan  1,36
18                             Sulawesi Barat  1,36
19                  Kepulauan Bangka Belitung  1,34
20                                      Jambi  1,32
21                                    Lampung  1,30
22                                       Riau  1,30
23                             Sumatera Utara  1,29
24                          Sulawesi Tenggara  1,25
25                                  Gorontalo  1,21
26                        Nusa Tenggara Timur  1,20
27                                       Aceh  1,18
28                               Maluku Utara  1,12
29                             Sulawesi Utara  1,11
30                            Sulawesi Tengah  1,10
31                             Kepulauan Riau  1,06
32                           Kalimantan Utara  0,92
33                                Papua Barat  0,71
34                                      Papua  0,70

In [9]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

In [10]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [11]:
final = concat.copy()
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', 'rasio']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                           rasio
provinsi
DKI Jakarta                 7.73
Bali                        2.11
Kalimantan Timur            1.74
Maluku                      1.69
Jawa Barat                  1.68
DI Yogyakarta               1.55
Jawa Tengah                 1.53
Kalimantan Selatan          1.50
Banten                      1.50
Sumatera Barat              1.50
Sulawesi Selatan            1.47
Jawa Timur                  1.45
Kalimantan Tengah           1.44
Bengkulu                    1.41
Kalimantan Barat            1.39
Nusa Tenggara Barat         1.38
Sumatera Selatan            1.36
Sulawesi Barat              1.36
Kepulauan Bangka Belitung   1.34
Jambi                       1.32
Lampung                     1.30
Riau                        1.30
Sumatera Utara              1.29
Sulawesi Tenggara           1.25
Gorontalo                   1.21
Nusa Tenggara Timur         1.20
Aceh                        1.18
Maluku Utara                1.12
Sulawesi Utara              1.11
Sulawesi Tengah             1.10
Kepulauan Riau              1.06
Kalimantan Utara            0.92
Papua Barat                 0.71
Papua                       0.70

In [12]:
final.to_csv('output/2017_rasio_puskesmas_per_kecamatan.csv')