In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [2]:
file = 'Profil-Kesehatan-Indonesia-tahun-2017.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (280, 30, 660, 570), pages = '71')
df = data[0]
df = df[1:]
df

   PUSKESMAS YANG MENYELENGGARAKAN PELAYANAN KESEHATAN TRADISIONAL
1                                         Lampung 255
2                                Sulawesi Selatan 188
3                                     Jawa Tengah 174
4                                      Jawa Timur 162
5                                            Aceh 151
6                                      Jawa Barat 147
7                              Kalimantan Selatan 146
8                             Nusa Tenggara Barat 134
9                                          Banten 134
10                                    DKI Jakarta 134
11                               Sumatera Selatan 134
12                                          Jambi 126
13                                           Bali 121
14                                 Sumatera Utara 115
15                                           Riau 107
16                                 Sulawesi Utara 100
17                                Kalimantan Timur 98
18                                 Sulawesi Tengah 84
19                                          Maluku 81
20                                Kalimantan Barat 80
21                                    Maluku Utara 73
22                                  Kepulauan Riau 71
23                                  Sumatera Barat 65
24                               Kalimantan Tengah 63
25                                   DI Yogyakarta 62
26                       Kepulauan Bangka Belitung 62
27                               Sulawesi Tenggara 61
28                                        Bengkulu 61
29                                       Gorontalo 55
30                             Nusa Tenggara Timur 45
31                                Kalimantan Utara 36
32                                  Sulawesi Barat 33
33                                     Papua Barat 28
34                                           Papua 24

In [3]:
concat = df.copy()
split = concat.iloc[:,0].str.split(' ')
# isna = concat[1].isna()
concat.loc[:, 1] = split.str[-1]
concat.iloc[:, 0] = split.str[:-1].str.join(' ') 
# concat.columns = np.arange(2)
concat

   PUSKESMAS YANG MENYELENGGARAKAN PELAYANAN KESEHATAN TRADISIONAL    1
1                                             Lampung               255
2                                    Sulawesi Selatan               188
3                                         Jawa Tengah               174
4                                          Jawa Timur               162
5                                                Aceh               151
6                                          Jawa Barat               147
7                                  Kalimantan Selatan               146
8                                 Nusa Tenggara Barat               134
9                                              Banten               134
10                                        DKI Jakarta               134
11                                   Sumatera Selatan               134
12                                              Jambi               126
13                                               Bali               121
14                                     Sumatera Utara               115
15                                               Riau               107
16                                     Sulawesi Utara               100
17                                   Kalimantan Timur                98
18                                    Sulawesi Tengah                84
19                                             Maluku                81
20                                   Kalimantan Barat                80
21                                       Maluku Utara                73
22                                     Kepulauan Riau                71
23                                     Sumatera Barat                65
24                                  Kalimantan Tengah                63
25                                      DI Yogyakarta                62
26                          Kepulauan Bangka Belitung                62
27                                  Sulawesi Tenggara                61
28                                           Bengkulu                61
29                                          Gorontalo                55
30                                Nusa Tenggara Timur                45
31                                   Kalimantan Utara                36
32                                     Sulawesi Barat                33
33                                        Papua Barat                28
34                                              Papua                24

In [4]:
final = concat.copy()
final[1] = final[1].str.replace('.', '', regex=False).astype(np.int_)
final.columns = ['provinsi', 'jumlah']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                           jumlah
provinsi
Lampung                       255
Sulawesi Selatan              188
Jawa Tengah                   174
Jawa Timur                    162
Aceh                          151
Jawa Barat                    147
Kalimantan Selatan            146
Nusa Tenggara Barat           134
Banten                        134
DKI Jakarta                   134
Sumatera Selatan              134
Jambi                         126
Bali                          121
Sumatera Utara                115
Riau                          107
Sulawesi Utara                100
Kalimantan Timur               98
Sulawesi Tengah                84
Maluku                         81
Kalimantan Barat               80
Maluku Utara                   73
Kepulauan Riau                 71
Sumatera Barat                 65
Kalimantan Tengah              63
DI Yogyakarta                  62
Kepulauan Bangka Belitung      62
Sulawesi Tenggara              61
Bengkulu                       61
Gorontalo                      55
Nusa Tenggara Timur            45
Kalimantan Utara               36
Sulawesi Barat                 33
Papua Barat                    28
Papua                          24

In [5]:
final.to_csv('output/2017_jumlah_puskesmas_pelayanan_kesehatan_tradisional.csv')