In [8]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [9]:
file = 'Profil-Kesehatan-Indonesia-tahun-2017.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (80, 80, 480, 510), pages = '82')
df = data[0]
df = df.loc[1:]
df

   RASIO TEMPAT TIDUR RUMAH SAKIT PER 1.000 PENDUDUK DI INDONESIA
1                                    DKI Jakarta 2,24
2                                 Sulawesi Utara 2,15
3                                  DI Yogyakarta 1,83
4                                           Aceh 1,72
5                                 Sumatera Utara 1,63
6                               Kalimantan Timur 1,62
7                                           Bali 1,58
8                               Sulawesi Selatan 1,51
9                               Kalimantan Utara 1,50
10                                   Papua Barat 1,47
11                                Kepulauan Riau 1,46
12                               Sulawesi Tengah 1,42
13                                     Gorontalo 1,33
14                                Sumatera Barat 1,33
15                                        Maluku 1,28
16                                  Maluku Utara 1,24
17                     Kepulauan Bangka Belitung 1,23
18                            Kalimantan Selatan 1,22
19                                      Bengkulu 1,20
20                                         Papua 1,19
21                                         Jambi 1,14
22                                   Jawa Tengah 1,14
23                              Sumatera Selatan 1,05
24                                    Jawa Timur 1,05
25                              Kalimantan Barat 1,03
26                             Sulawesi Tenggara 1,03
27                                          Riau 0,99
28                                       Lampung 0,88
29                                        Banten 0,88
30                                    Jawa Barat 0,83
31                                Sulawesi Barat 0,83
32                           Nusa Tenggara Timur 0,82
33                             Kalimantan Tengah 0,79
34                           Nusa Tenggara Barat 0,68

In [10]:
df.columns = np.arange(1)
# jakarta = df.iloc[2,:]
df

df.loc[:,1] = df.iloc[:,0].str.split(' ').str[-1]
df.iloc[:,0] = df.iloc[:,0].str.split(' ').str[:-1].str.join(' ')
df

C:\Users\KEMENKEU\AppData\Local\Temp\ipykernel_113864\1316500034.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[:,1] = df.iloc[:,0].str.split(' ').str[-1]
C:\Users\KEMENKEU\AppData\Local\Temp\ipykernel_113864\1316500034.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[:,0] = df.iloc[:,0].str.split(' ').str[:-1].str.join(' ')

                            0     1
1                 DKI Jakarta  2,24
2              Sulawesi Utara  2,15
3               DI Yogyakarta  1,83
4                        Aceh  1,72
5              Sumatera Utara  1,63
6            Kalimantan Timur  1,62
7                        Bali  1,58
8            Sulawesi Selatan  1,51
9            Kalimantan Utara  1,50
10                Papua Barat  1,47
11             Kepulauan Riau  1,46
12            Sulawesi Tengah  1,42
13                  Gorontalo  1,33
14             Sumatera Barat  1,33
15                     Maluku  1,28
16               Maluku Utara  1,24
17  Kepulauan Bangka Belitung  1,23
18         Kalimantan Selatan  1,22
19                   Bengkulu  1,20
20                      Papua  1,19
21                      Jambi  1,14
22                Jawa Tengah  1,14
23           Sumatera Selatan  1,05
24                 Jawa Timur  1,05
25           Kalimantan Barat  1,03
26          Sulawesi Tenggara  1,03
27                       Riau  0,99
28                    Lampung  0,88
29                     Banten  0,88
30                 Jawa Barat  0,83
31             Sulawesi Barat  0,83
32        Nusa Tenggara Timur  0,82
33          Kalimantan Tengah  0,79
34        Nusa Tenggara Barat  0,68

In [11]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

In [12]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [13]:
final = df.copy()
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', 'rasio']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                           rasio
provinsi
DKI Jakarta                 2.24
Sulawesi Utara              2.15
DI Yogyakarta               1.83
Aceh                        1.72
Sumatera Utara              1.63
Kalimantan Timur            1.62
Bali                        1.58
Sulawesi Selatan            1.51
Kalimantan Utara            1.50
Papua Barat                 1.47
Kepulauan Riau              1.46
Sulawesi Tengah             1.42
Gorontalo                   1.33
Sumatera Barat              1.33
Maluku                      1.28
Maluku Utara                1.24
Kepulauan Bangka Belitung   1.23
Kalimantan Selatan          1.22
Bengkulu                    1.20
Papua                       1.19
Jambi                       1.14
Jawa Tengah                 1.14
Sumatera Selatan            1.05
Jawa Timur                  1.05
Kalimantan Barat            1.03
Sulawesi Tenggara           1.03
Riau                        0.99
Lampung                     0.88
Banten                      0.88
Jawa Barat                  0.83
Sulawesi Barat              0.83
Nusa Tenggara Timur         0.82
Kalimantan Tengah           0.79
Nusa Tenggara Barat         0.68

In [14]:
final.to_csv('output/2017_rasio_tempat_tidur_rs_per_1000_penduduk.csv')