In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [2]:
file = 'Profil-Kesehatan-Indonesia-tahun-2017.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (180, 30, 530, 570), pages = '67')
df = data[0]
df = df[1:]
df

   JUMLAH PUSKESMAS YANG MELAKSANAKAN PELAYANAN KESEHATAN KERJA DASAR
1                                      Jawa Timur 877
2                                      Jawa Barat 712
3                                     Jawa Tengah 486
4                                Sulawesi Selatan 327
5                                Sumatera Selatan 276
6                                  Sumatera Utara 252
7                                         Lampung 229
8                                     DKI Jakarta 213
9                                            Aceh 211
10                            Nusa Tenggara Timur 192
11                                 Sulawesi Utara 188
12                              Sulawesi Tenggara 185
13                                         Banten 171
14                             Kalimantan Selatan 150
15                            Nusa Tenggara Barat 149
16                                          Jambi 143
17                                           Riau 123
18                                 Sumatera Barat 122
19                                Sulawesi Tengah 117
20                                           Bali 107
21                                       Gorontalo 93
22                                   DI Yogyakarta 93
23                               Kalimantan Tengah 84
24                                        Bengkulu 81
25                                          Maluku 78
26                                Kalimantan Timur 74
27                                  Kepulauan Riau 67
28                       Kepulauan Bangka Belitung 62
29                                Kalimantan Barat 61
30                                  Sulawesi Barat 60
31                                    Maluku Utara 51
32                                           Papua 37
33                                     Papua Barat 20
34                                Kalimantan Utara 19

In [3]:
concat = df.copy()
split = concat.iloc[:,0].str.split(' ')
# isna = concat[1].isna()
concat.loc[:, 1] = split.str[-1]
concat.iloc[:, 0] = split.str[:-1].str.join(' ') 
# concat.columns = np.arange(2)
concat

   JUMLAH PUSKESMAS YANG MELAKSANAKAN PELAYANAN KESEHATAN KERJA DASAR    1
1                                          Jawa Timur                  877
2                                          Jawa Barat                  712
3                                         Jawa Tengah                  486
4                                    Sulawesi Selatan                  327
5                                    Sumatera Selatan                  276
6                                      Sumatera Utara                  252
7                                             Lampung                  229
8                                         DKI Jakarta                  213
9                                                Aceh                  211
10                                Nusa Tenggara Timur                  192
11                                     Sulawesi Utara                  188
12                                  Sulawesi Tenggara                  185
13                                             Banten                  171
14                                 Kalimantan Selatan                  150
15                                Nusa Tenggara Barat                  149
16                                              Jambi                  143
17                                               Riau                  123
18                                     Sumatera Barat                  122
19                                    Sulawesi Tengah                  117
20                                               Bali                  107
21                                          Gorontalo                   93
22                                      DI Yogyakarta                   93
23                                  Kalimantan Tengah                   84
24                                           Bengkulu                   81
25                                             Maluku                   78
26                                   Kalimantan Timur                   74
27                                     Kepulauan Riau                   67
28                          Kepulauan Bangka Belitung                   62
29                                   Kalimantan Barat                   61
30                                     Sulawesi Barat                   60
31                                       Maluku Utara                   51
32                                              Papua                   37
33                                        Papua Barat                   20
34                                   Kalimantan Utara                   19

In [4]:
final = concat.copy()
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.int_)
final.columns = ['provinsi', 'jumlah']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                           jumlah
provinsi
Jawa Timur                    877
Jawa Barat                    712
Jawa Tengah                   486
Sulawesi Selatan              327
Sumatera Selatan              276
Sumatera Utara                252
Lampung                       229
DKI Jakarta                   213
Aceh                          211
Nusa Tenggara Timur           192
Sulawesi Utara                188
Sulawesi Tenggara             185
Banten                        171
Kalimantan Selatan            150
Nusa Tenggara Barat           149
Jambi                         143
Riau                          123
Sumatera Barat                122
Sulawesi Tengah               117
Bali                          107
Gorontalo                      93
DI Yogyakarta                  93
Kalimantan Tengah              84
Bengkulu                       81
Maluku                         78
Kalimantan Timur               74
Kepulauan Riau                 67
Kepulauan Bangka Belitung      62
Kalimantan Barat               61
Sulawesi Barat                 60
Maluku Utara                   51
Papua                          37
Papua Barat                    20
Kalimantan Utara               19

In [5]:
final.to_csv('output/2017_jumlah_puskesmas_kesehatan_kerja_dasar.csv')