In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [5]:
file = 'Profil-Kesehatan-2021.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (120, 0, 740, 530), pages = '62')
df = data[0]
df.columns = np.arange(1)
# jakarta = df.iloc[2,:]
df = df.iloc[16:]
df

df[1] = df[0].str.split(' ').str[-1]
df[0] = df[0].str.split(' ').str[:-1].str.join(' ')
df

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')

C:\Users\satria.rahman\AppData\Local\Temp\ipykernel_19492\2489571036.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1] = df[0].str.split(' ').str[-1]
C:\Users\satria.rahman\AppData\Local\Temp\ipykernel_19492\2489571036.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[0] = df[0].str.split(' ').str[:-1].str.join(' ')

                            0     1
16                      Papua  42,6
17                     Maluku  23,0
18                Papua Barat  20,4
19               Maluku Utara  15,7
20          Sulawesi Tenggara  14,3
21                  Gorontalo  10,8
22        Nusa Tenggara Timur   9,6
23             Sulawesi Barat   6,1
24          Kalimantan Tengah   5,9
25            Sulawesi Tengah   3,8
26             Sumatera Utara   3,6
27           Kalimantan Utara   3,6
28           Kalimantan Barat   3,2
29                   Bengkulu   2,8
30           Sulawesi Selatan   2,6
31             Sulawesi Utara   2,6
32           Sumatera Selatan   2,3
33                       Aceh   2,2
34             Kepulauan Riau   2,2
35             Sumatera Barat   1,8
36         Kalimantan Selatan   0,8
37                 Jawa Barat   0,7
38                 Jawa Timur   0,7
39           Kalimantan Timur   0,5
40                      Jambi   0,5
41                       Riau   0,4
42                     Banten   0,4
43                    Lampung   0,3
44                Jawa Tengah   0,1
45        Nusa Tenggara Barat   0,0
46                       Bali   0,0
47              DI Yogyakarta   0,0
48                DKI Jakarta   0,0
49  Kepulauan Bangka Belitung   0,0

In [49]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

                            0      1
1                   Indonesia   89,7
2            Kalimantan Utara  100,0
3                        Bali  100,0
4               DI Yogyakarta  100,0
5   Kepulauan Bangka Belitung  100,0
6                    Bengkulu  100,0
7                  Jawa Timur   99,5
8                 Jawa Tengah   99,4
9                   Gorontalo   98,9
10         Kalimantan Selatan   98,7
11           Sulawesi Selatan   98,5
12             Sumatera Barat   98,2
13           Kalimantan Timur   97,3
14           Sumatera Selatan   97,1
15            Sulawesi Tengah   95,7
16                 Jawa Barat   94,9
17                    Lampung   94,9
18          Kalimantan Tengah   94,6
19             Kepulauan Riau   94,3
20                     Banten   94,3
21        Nusa Tenggara Barat   93,7
22           Kalimantan Barat   93,5
23                       Aceh   92,8
24                       Riau   92,6
25             Sumatera Utara   91,9
26                      Jambi   90,8
27          Sulawesi Tenggara   90,1
28        Nusa Tenggara Timur   89,5
29             Sulawesi Barat   88,5
30             Sulawesi Utara   86,7
31               Maluku Utara   76,9
32                     Maluku   72,6
33                DKI Jakarta   47,9
34                Papua Barat   44,7
35                      Papua   28,0

In [60]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [6]:
final = df.copy()
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', 'Persentase Puskesmas Tanpa Dokter']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                           Persentase Puskesmas Tanpa Dokter
provinsi
Papua                                                   42.6
Maluku                                                  23.0
Papua Barat                                             20.4
Maluku Utara                                            15.7
Sulawesi Tenggara                                       14.3
Gorontalo                                               10.8
Nusa Tenggara Timur                                      9.6
Sulawesi Barat                                           6.1
Kalimantan Tengah                                        5.9
Sulawesi Tengah                                          3.8
Sumatera Utara                                           3.6
Kalimantan Utara                                         3.6
Kalimantan Barat                                         3.2
Bengkulu                                                 2.8
Sulawesi Selatan                                         2.6
Sulawesi Utara                                           2.6
Sumatera Selatan                                         2.3
Aceh                                                     2.2
Kepulauan Riau                                           2.2
Sumatera Barat                                           1.8
Kalimantan Selatan                                       0.8
Jawa Barat                                               0.7
Jawa Timur                                               0.7
Kalimantan Timur                                         0.5
Jambi                                                    0.5
Riau                                                     0.4
Banten                                                   0.4
Lampung                                                  0.3
Jawa Tengah                                              0.1
Nusa Tenggara Barat                                      0.0
Bali                                                     0.0
DI Yogyakarta                                            0.0
DKI Jakarta                                              0.0
Kepulauan Bangka Belitung                                0.0

In [7]:
final.to_csv('output/2021_Persentase_Puskesmas_Tanpa_Dokter.csv')