In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [2]:
file = 'Profil-Kesehatan-2021.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (0, 80, 540, 510), pages = '81')
df = data[0]
df.columns = np.arange(3)
# jakarta = df.iloc[2,:]
# df = df.iloc[16:]
df = df[4:]
df

# df[1] = df[0].str.split(' ').str[-1]
# df[0] = df[0].str.split(' ').str[:-1].str.join(' ')
# df = df[3:]
# df

concat = df.copy()
split = concat[0].str.split(' ')
isna = concat[1].isna()
concat.loc[isna, 1] = concat[2]
concat = concat.drop(2, axis=1)
concat
# concat.loc[isna, 0] = split.str[:-1].str.join(' ') 
# concat = concat[2:]
# concat

                       0     1
4         Sulawesi Utara  2,70
5            DKI Jakarta  2,37
6            Papua Barat  2,07
7                   Aceh  1,94
8                   Bali  1,93
9       Kalimantan Utara  1,90
10      Sulawesi Selatan  1,87
11             Gorontalo  1,84
12      Kalimantan Timur  1,83
13         DI Yogyakarta  1,80
14        Kepulauan Riau  1,70
15                Maluku  1,69
16       Sulawesi Tengah  1,65
17  Kep. Bangka Belitung  1,63
18        Sumatera Utara  1,63
19    Kalimantan Selatan  1,50
20     Kalimantan Tengah  1,47
21          Maluku Utara  1,42
22              Bengkulu  1,41
23                 Papua  1,35
24        Sumatera Barat  1,35
25     Sulawesi Tenggara  1,35
26           Jawa Tengah  1,31
27                 Jambi  1,30
28            Jawa Timur  1,27
29      Kalimantan Barat  1,27
30                  Riau  1,19
31   Nusa Tenggara Barat  1,14
32      Sumatera Selatan  1,12
33        Sulawesi Barat  1,07
34            Jawa Barat  1,04
35                Banten  1,03
36   Nusa Tenggara Timur  1,00
37               Lampung  0,95

In [3]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

In [60]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [4]:
final = concat.copy()
final[1] = final[1].astype(str)
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', 'Rasio Tempat Tidur Rumah Sakit Per 1000 Penduduk']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                      Rasio Tempat Tidur Rumah Sakit Per 1000 Penduduk
provinsi
Sulawesi Utara                                                    2.70
DKI Jakarta                                                       2.37
Papua Barat                                                       2.07
Aceh                                                              1.94
Bali                                                              1.93
Kalimantan Utara                                                  1.90
Sulawesi Selatan                                                  1.87
Gorontalo                                                         1.84
Kalimantan Timur                                                  1.83
DI Yogyakarta                                                     1.80
Kepulauan Riau                                                    1.70
Maluku                                                            1.69
Sulawesi Tengah                                                   1.65
Kep. Bangka Belitung                                              1.63
Sumatera Utara                                                    1.63
Kalimantan Selatan                                                1.50
Kalimantan Tengah                                                 1.47
Maluku Utara                                                      1.42
Bengkulu                                                          1.41
Papua                                                             1.35
Sumatera Barat                                                    1.35
Sulawesi Tenggara                                                 1.35
Jawa Tengah                                                       1.31
Jambi                                                             1.30
Jawa Timur                                                        1.27
Kalimantan Barat                                                  1.27
Riau                                                              1.19
Nusa Tenggara Barat                                               1.14
Sumatera Selatan                                                  1.12
Sulawesi Barat                                                    1.07
Jawa Barat                                                        1.04
Banten                                                            1.03
Nusa Tenggara Timur                                               1.00
Lampung                                                           0.95

In [5]:
final.to_csv('output/2021_Rasio_Tempat_Tidur_RS_Per_1000_Penduduk.csv')