In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [82]:
file = 'Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (20, 0, 660, 520), pages = '60')
df = data[0]
df.columns = np.arange(1)
# jakarta = df.iloc[2,:]
df = df.iloc[16:]
df

df[1] = df[0].str.split(' ').str[-1]
df[0] = df[0].str.split(' ').str[:-1].str.join(' ')
df

C:\Users\satria.rahman\AppData\Local\Temp\ipykernel_8860\2145030469.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1] = df[0].str.split(' ').str[-1]
C:\Users\satria.rahman\AppData\Local\Temp\ipykernel_8860\2145030469.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[0] = df[0].str.split(' ').str[:-1].str.join(' ')

                       0      1
16             Gorontalo  100,0
17       Sulawesi Tengah  100,0
18      Kalimantan Utara  100,0
19         DI Yogyakarta  100,0
20            Jawa Barat  100,0
21           DKI Jakarta  100,0
22              Bengkulu  100,0
23                 Jambi   90,9
24        Sumatera Utara   90,9
25      Kalimantan Timur   90,0
26                Banten   87,5
27        Kepulauan Riau   85,7
28  Kep. Bangka Belitung   85,7
29        Sulawesi Barat   83,3
30            Jawa Timur   81,6
31      Sulawesi Selatan   79,2
32        Sumatera Barat   78,9
33     Kalimantan Tengah   78,6
34   Nusa Tenggara Timur   77,3
35           Jawa Tengah   74,3
36          Maluku Utara   70,0
37     Sulawesi Tenggara   64,7
38      Sumatera Selatan   58,8
39                  Riau   58,3
40               Lampung   46,7
41      Kalimantan Barat   42,9
42   Nusa Tenggara Barat   40,0
43                  Aceh   26,1
44                  Bali   22,2
45        Sulawesi Utara   20,0
46                Maluku    9,1
47    Kalimantan Selatan    7,7

In [49]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

                            0      1
1                   Indonesia   89,7
2            Kalimantan Utara  100,0
3                        Bali  100,0
4               DI Yogyakarta  100,0
5   Kepulauan Bangka Belitung  100,0
6                    Bengkulu  100,0
7                  Jawa Timur   99,5
8                 Jawa Tengah   99,4
9                   Gorontalo   98,9
10         Kalimantan Selatan   98,7
11           Sulawesi Selatan   98,5
12             Sumatera Barat   98,2
13           Kalimantan Timur   97,3
14           Sumatera Selatan   97,1
15            Sulawesi Tengah   95,7
16                 Jawa Barat   94,9
17                    Lampung   94,9
18          Kalimantan Tengah   94,6
19             Kepulauan Riau   94,3
20                     Banten   94,3
21        Nusa Tenggara Barat   93,7
22           Kalimantan Barat   93,5
23                       Aceh   92,8
24                       Riau   92,6
25             Sumatera Utara   91,9
26                      Jambi   90,8
27          Sulawesi Tenggara   90,1
28        Nusa Tenggara Timur   89,5
29             Sulawesi Barat   88,5
30             Sulawesi Utara   86,7
31               Maluku Utara   76,9
32                     Maluku   72,6
33                DKI Jakarta   47,9
34                Papua Barat   44,7
35                      Papua   28,0

In [60]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [83]:
final = df.copy()
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', 'Yang Melaksanakan Kesehatan Kerja']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                      Yang Melaksanakan Kesehatan Kerja
provinsi
Gorontalo                                         100.0
Sulawesi Tengah                                   100.0
Kalimantan Utara                                  100.0
DI Yogyakarta                                     100.0
Jawa Barat                                        100.0
DKI Jakarta                                       100.0
Bengkulu                                          100.0
Jambi                                              90.9
Sumatera Utara                                     90.9
Kalimantan Timur                                   90.0
Banten                                             87.5
Kepulauan Riau                                     85.7
Kep. Bangka Belitung                               85.7
Sulawesi Barat                                     83.3
Jawa Timur                                         81.6
Sulawesi Selatan                                   79.2
Sumatera Barat                                     78.9
Kalimantan Tengah                                  78.6
Nusa Tenggara Timur                                77.3
Jawa Tengah                                        74.3
Maluku Utara                                       70.0
Sulawesi Tenggara                                  64.7
Sumatera Selatan                                   58.8
Riau                                               58.3
Lampung                                            46.7
Kalimantan Barat                                   42.9
Nusa Tenggara Barat                                40.0
Aceh                                               26.1
Bali                                               22.2
Sulawesi Utara                                     20.0
Maluku                                              9.1
Kalimantan Selatan                                  7.7

In [12]:
final.to_csv('output/9_Jenis_TenagaKesehatan_SesuaiStandar.csv')