In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [3]:
file = 'Profil-Kesehatan-2021.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (30, 0, 530, 480), pages = '79')
df = data[0]
df.columns = np.arange(1)
# jakarta = df.iloc[2,:]
# df = df.iloc[16:]
df

df[1] = df[0].str.split(' ').str[-1]
df[0] = df[0].str.split(' ').str[:-1].str.join(' ')
df = df[3:]
df

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ') 
# concat = concat[2:]
# concat

                            0      1
3   Kepulauan Bangka Belitung  100,0
4                        Aceh  100,0
5                 Jawa Tengah   94,6
6               DI Yogyakarta   88,9
7                  Jawa Timur   86,7
8              Sumatera Utara   84,8
9            Kalimantan Timur   83,3
10                       Bali   81,8
11                     Banten   81,8
12                    Lampung   81,3
13                 Jawa Barat   80,8
14           Kalimantan Utara   80,0
15                   Bengkulu   80,0
16           Sulawesi Selatan   78,1
17                  Gorontalo   77,8
18                      Jambi   75,0
19                       Riau   75,0
20         Kalimantan Selatan   72,2
21          Kalimantan Tengah   71,4
22        Nusa Tenggara Timur   71,4
23             Sumatera Barat   71,4
24        Nusa Tenggara Barat   69,2
25           Sumatera Selatan   69,0
26                Papua Barat   66,7
27            Sulawesi Tengah   60,9
28             Kepulauan Riau   60,0
29           Kalimantan Barat   57,9
30               Maluku Utara   57,1
31             Sulawesi Barat   57,1
32             Sulawesi Utara   52,9
33          Sulawesi Tenggara   50,0
34                     Maluku   38,5
35                      Papua   31,6
36               DKI Jakarta*    0,0

In [49]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

                            0      1
1                   Indonesia   89,7
2            Kalimantan Utara  100,0
3                        Bali  100,0
4               DI Yogyakarta  100,0
5   Kepulauan Bangka Belitung  100,0
6                    Bengkulu  100,0
7                  Jawa Timur   99,5
8                 Jawa Tengah   99,4
9                   Gorontalo   98,9
10         Kalimantan Selatan   98,7
11           Sulawesi Selatan   98,5
12             Sumatera Barat   98,2
13           Kalimantan Timur   97,3
14           Sumatera Selatan   97,1
15            Sulawesi Tengah   95,7
16                 Jawa Barat   94,9
17                    Lampung   94,9
18          Kalimantan Tengah   94,6
19             Kepulauan Riau   94,3
20                     Banten   94,3
21        Nusa Tenggara Barat   93,7
22           Kalimantan Barat   93,5
23                       Aceh   92,8
24                       Riau   92,6
25             Sumatera Utara   91,9
26                      Jambi   90,8
27          Sulawesi Tenggara   90,1
28        Nusa Tenggara Timur   89,5
29             Sulawesi Barat   88,5
30             Sulawesi Utara   86,7
31               Maluku Utara   76,9
32                     Maluku   72,6
33                DKI Jakarta   47,9
34                Papua Barat   44,7
35                      Papua   28,0

In [60]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [4]:
final = df.copy()
# final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', 'Persentase RS KabKota Kelas C Memiliki 4 DokterSpesialis Dasar & 3 DokterSpesialis Penunjang']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                          Persentase RS KabKota Kelas C Memiliki 4 DokterSpesialis Dasar & 3 DokterSpesialis Penunjang
provinsi
Kepulauan Bangka Belitung                                              100,0
Aceh                                                                   100,0
Jawa Tengah                                                             94,6
DI Yogyakarta                                                           88,9
Jawa Timur                                                              86,7
Sumatera Utara                                                          84,8
Kalimantan Timur                                                        83,3
Bali                                                                    81,8
Banten                                                                  81,8
Lampung                                                                 81,3
Jawa Barat                                                              80,8
Kalimantan Utara                                                        80,0
Bengkulu                                                                80,0
Sulawesi Selatan                                                        78,1
Gorontalo                                                               77,8
Jambi                                                                   75,0
Riau                                                                    75,0
Kalimantan Selatan                                                      72,2
Kalimantan Tengah                                                       71,4
Nusa Tenggara Timur                                                     71,4
Sumatera Barat                                                          71,4
Nusa Tenggara Barat                                                     69,2
Sumatera Selatan                                                        69,0
Papua Barat                                                             66,7
Sulawesi Tengah                                                         60,9
Kepulauan Riau                                                          60,0
Kalimantan Barat                                                        57,9
Maluku Utara                                                            57,1
Sulawesi Barat                                                          57,1
Sulawesi Utara                                                          52,9
Sulawesi Tenggara                                                       50,0
Maluku                                                                  38,5
Papua                                                                   31,6
DKI Jakarta*                                                             0,0

In [5]:
final.to_csv('output/2021_Persentase_RS_KabKota_KelasC_4_DokterSpesialis_Dasar_3_DokterSpesialis_Penunjang.csv')