In [1]:
import tabula.io as tb
import pandas as pd
import numpy as np
import math

In [9]:
file = 'Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
# file = 'https://github.com/dyanmg/health-data-analysis/raw/master/Profil-Kesehatan-Indonesia-Tahun-2020.pdf'
data = tb.read_pdf(file, area = (40, 0, 440, 510), pages = '58')
df = data[0]
df.columns = np.arange(1)
# jakarta = df.iloc[2,:]
df = df.iloc[3:]
df

df[1] = df[0].str.split(' ').str[-1]
df[0] = df[0].str.split(' ').str[:-1].str.join(' ')
df

C:\Users\satria.rahman\AppData\Local\Temp\ipykernel_23596\852361969.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[1] = df[0].str.split(' ').str[-1]
C:\Users\satria.rahman\AppData\Local\Temp\ipykernel_23596\852361969.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[0] = df[0].str.split(' ').str[:-1].str.join(' ')

                            0     1
3               DI Yogyakarta  88,4
4   Kepulauan Bangka Belitung  81,3
5                 Jawa Tengah  70,6
6              Sumatera Barat  68,3
7         Nusa Tenggara Barat  54,9
8                        Aceh  54,6
9                  Jawa Timur  54,1
10         Kalimantan Selatan  53,8
11           Sulawesi Selatan  52,1
12                       Bali  51,7
13                     Banten  51,6
14           Kalimantan Timur  51,3
15           Kalimantan Utara  48,3
16             Kepulauan Riau  47,8
17             Sulawesi Barat  43,3
18                       Riau  42,4
19                      Jambi  41,7
20                 Jawa Barat  36,6
21           Sumatera Selatan  29,2
22           Kalimantan Barat  28,5
23             Sumatera Utara  27,6
24                  Gorontalo  26,9
25            Sulawesi Tengah  26,6
26                    Lampung  26,4
27          Sulawesi Tenggara  25,7
28        Nusa Tenggara Timur  22,9
29                   Bengkulu  22,9
30          Kalimantan Tengah  20,7
31             Sulawesi Utara  17,7
32               Maluku Utara  17,1
33                DKI Jakarta  13,8
34                     Maluku  10,6
35                Papua Barat   8,5
36                      Papua   6,1

In [49]:
# df[2] = df[0].str.split(' ')
# df[2] = df[0].str.split(' ').str[-1].str.replace(',', '.')
# process = df.copy()
# process['Gabung'] = process[0] + " " + process[1].fillna('')
# process[0]

#process[1] = process[0].str.split(' ').str[-1]
#process[0] = process[0].str.split(' ').str[:-1].str.join(' ')
# process

# concat = df.copy()
# split = concat[0].str.split(' ')
# isna = concat[1].isna()
# concat.loc[isna, 1] = split.str[-1]
# concat.loc[isna, 0] = split.str[:-1].str.join(' ')
# concat

                            0      1
1                   Indonesia   89,7
2            Kalimantan Utara  100,0
3                        Bali  100,0
4               DI Yogyakarta  100,0
5   Kepulauan Bangka Belitung  100,0
6                    Bengkulu  100,0
7                  Jawa Timur   99,5
8                 Jawa Tengah   99,4
9                   Gorontalo   98,9
10         Kalimantan Selatan   98,7
11           Sulawesi Selatan   98,5
12             Sumatera Barat   98,2
13           Kalimantan Timur   97,3
14           Sumatera Selatan   97,1
15            Sulawesi Tengah   95,7
16                 Jawa Barat   94,9
17                    Lampung   94,9
18          Kalimantan Tengah   94,6
19             Kepulauan Riau   94,3
20                     Banten   94,3
21        Nusa Tenggara Barat   93,7
22           Kalimantan Barat   93,5
23                       Aceh   92,8
24                       Riau   92,6
25             Sumatera Utara   91,9
26                      Jambi   90,8
27          Sulawesi Tenggara   90,1
28        Nusa Tenggara Timur   89,5
29             Sulawesi Barat   88,5
30             Sulawesi Utara   86,7
31               Maluku Utara   76,9
32                     Maluku   72,6
33                DKI Jakarta   47,9
34                Papua Barat   44,7
35                      Papua   28,0

In [60]:
# concat = pd.concat([concat.to_frame().T, process])
# concat

In [11]:
final = df.copy()
final[1] = final[1].str.replace(',', '.', regex=False).astype(np.double)
final.columns = ['provinsi', '9 Jenis Tenaga Kesahatan Sesuai Standar']
# final.reset_index(drop=True, inplace=True)
final.set_index('provinsi', inplace=True)
final

                           9 Jenis Tenaga Kesahatan Sesuai Standar
provinsi
DI Yogyakarta                                                 88.4
Kepulauan Bangka Belitung                                     81.3
Jawa Tengah                                                   70.6
Sumatera Barat                                                68.3
Nusa Tenggara Barat                                           54.9
Aceh                                                          54.6
Jawa Timur                                                    54.1
Kalimantan Selatan                                            53.8
Sulawesi Selatan                                              52.1
Bali                                                          51.7
Banten                                                        51.6
Kalimantan Timur                                              51.3
Kalimantan Utara                                              48.3
Kepulauan Riau                                                47.8
Sulawesi Barat                                                43.3
Riau                                                          42.4
Jambi                                                         41.7
Jawa Barat                                                    36.6
Sumatera Selatan                                              29.2
Kalimantan Barat                                              28.5
Sumatera Utara                                                27.6
Gorontalo                                                     26.9
Sulawesi Tengah                                               26.6
Lampung                                                       26.4
Sulawesi Tenggara                                             25.7
Nusa Tenggara Timur                                           22.9
Bengkulu                                                      22.9
Kalimantan Tengah                                             20.7
Sulawesi Utara                                                17.7
Maluku Utara                                                  17.1
DKI Jakarta                                                   13.8
Maluku                                                        10.6
Papua Barat                                                    8.5
Papua                                                          6.1

In [12]:
final.to_csv('output/9_Jenis_TenagaKesehatan_SesuaiStandar.csv')